#!/bin/sh
set -eu

prefix="${PREFIX:-/usr/local}"
repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
lib_dir="$prefix/lib/ironkey-vp50"
share_dir="$prefix/share/ironkey-vp50"
system_install="${IRONKEY_VP50_SYSTEM_INSTALL:-0}"
target_user="${SUDO_USER:-}"

if [ "$(id -u)" -ne 0 ]; then
    echo "Run as root: sudo ./install-desktop.sh" >&2
    exit 1
fi

if [ -z "$target_user" ] || [ "$target_user" = "root" ]; then
    echo "Run with sudo from the desktop user that should get autostart." >&2
    exit 1
fi

target_home=$(getent passwd "$target_user" | cut -d: -f6)
if [ -z "$target_home" ] || [ ! -d "$target_home" ]; then
    echo "Could not find home directory for $target_user." >&2
    exit 1
fi

if [ "$system_install" = "1" ]; then
    prefix="/usr"
    lib_dir="$prefix/lib/ironkey-vp50"
    share_dir="$prefix/share/ironkey-vp50"
else
    install -Dm755 "$repo_dir/ironkey_vp50.py" "$lib_dir/ironkey_vp50.py"
    install -Dm755 "$repo_dir/ironkey_vp50_desktop_agent.py" "$lib_dir/ironkey_vp50_desktop_agent.py"
    install -Dm755 "$repo_dir/ironkey_vp50_kde_agent.py" "$lib_dir/ironkey_vp50_kde_agent.py"

    install -d -m 755 "$prefix/bin"

    cat > "$prefix/bin/ironkey-vp50" <<EOF
#!/bin/sh
exec python3 "$lib_dir/ironkey_vp50.py" "\$@"
EOF
    chmod 755 "$prefix/bin/ironkey-vp50"

    cat > "$prefix/bin/ironkey-vp50-desktop-agent" <<EOF
#!/bin/sh
exec python3 "$lib_dir/ironkey_vp50_desktop_agent.py" "\$@"
EOF
    chmod 755 "$prefix/bin/ironkey-vp50-desktop-agent"

    cat > "$prefix/bin/ironkey-vp50-kde-agent" <<EOF
#!/bin/sh
exec "$prefix/bin/ironkey-vp50-desktop-agent" "\$@"
EOF
    chmod 755 "$prefix/bin/ironkey-vp50-kde-agent"

    cat > "$prefix/bin/ironkey-vp50-root-unlock" <<EOF
#!/bin/sh
set -eu
case "\${1:-}" in
    /dev/sg[0-9]|/dev/sg[0-9][0-9])
        exec python3 "$lib_dir/ironkey_vp50.py" unlock --sg "\$1" --pvc --password-stdin --yes
        ;;
    *)
        echo "usage: ironkey-vp50-root-unlock /dev/sgN" >&2
        exit 2
        ;;
esac
EOF
    chmod 755 "$prefix/bin/ironkey-vp50-root-unlock"
fi

cat > /etc/sudoers.d/ironkey-vp50 <<EOF
# Allow the desktop user-session agent to send exactly one VP50 unlock attempt
# through the root-only SG_IO data-out path. The IronKey password is passed on
# stdin and is never stored in this file or in process arguments.
$target_user ALL=(root) NOPASSWD: $prefix/bin/ironkey-vp50-root-unlock /dev/sg*
EOF
chmod 440 /etc/sudoers.d/ironkey-vp50
visudo -cf /etc/sudoers.d/ironkey-vp50 >/dev/null

cat > /etc/udev/rules.d/90-ironkey-vp50.rules <<EOF
# Generated by ironkey-vp50 install-desktop.sh.
# Give $target_user access to Kingston IronKey VaultPrivacy50 SCSI generic nodes.
ACTION=="add|change", SUBSYSTEM=="scsi_generic", ATTRS{idVendor}=="0951", ATTRS{idProduct}=="1576", OWNER="$target_user", MODE="0600", TAG+="seat", TAG+="uaccess"
EOF

autostart_dir="$target_home/.config/autostart"
install -d -m 755 -o "$target_user" -g "$target_user" "$autostart_dir"
if [ "$system_install" = "1" ]; then
    desktop_file="$share_dir/ironkey-vp50-agent.desktop"
else
    desktop_file="$repo_dir/desktop/ironkey-vp50-agent.desktop"
fi
install -m 644 -o "$target_user" -g "$target_user" "$desktop_file" "$autostart_dir/ironkey-vp50-agent.desktop"

udevadm control --reload-rules
udevadm trigger --subsystem-match=scsi_generic || true

target_uid=$(id -u "$target_user")
if [ -d "/run/user/$target_uid" ]; then
    pkill -u "$target_user" -f 'ironkey-vp50-desktop-agent|ironkey_vp50_desktop_agent.py|ironkey-vp50-kde-agent|ironkey_vp50_kde_agent.py' >/dev/null 2>&1 || true
    session_env=$(runuser -u "$target_user" -- systemctl --user show-environment 2>/dev/null | grep -E '^(DBUS_SESSION_BUS_ADDRESS|DISPLAY|WAYLAND_DISPLAY|XDG_CURRENT_DESKTOP|XDG_RUNTIME_DIR)=' || true)
    env_args=""
    for item in $session_env; do
        env_args="$env_args $item"
    done
    runuser -u "$target_user" -- sh -c \
        "env $env_args nohup '$prefix/bin/ironkey-vp50-desktop-agent' >/tmp/ironkey-vp50-desktop-agent.log 2>&1 &"
fi

echo "Installed IronKey VP50 desktop integration."
echo "The desktop agent is installed for $target_user and was started if a desktop session was available."
echo "If no prompt appears, check /tmp/ironkey-vp50-desktop-agent.log."
